import { DollarSign, Users, Calendar, Star, Car, Package, Wrench } from "lucide-react"

// Landing page stats
export const stats = [
  { value: "10,000+", label: "Verified Professionals" },
  { value: "50,000+", label: "Happy Customers" },
  { value: "25+", label: "Cities Covered" },
  { value: "4.8/5", label: "Average Rating" },
]

// Featured listings for homepage
export const featuredListings = [
  {
    id: 1,
    name: "AutoCare Pro Garage",
    type: "garage",
    location: "Downtown, City Center",
    rating: 4.9,
    reviews: 127,
    description: "Full-service automotive repair with certified technicians and modern equipment.",
    services: ["Oil Change", "Brake Repair", "Engine Diagnostics", "Transmission", "AC Service"],
    priceRange: "50-200",
  },
  {
    id: 2,
    name: "Mike's Mobile Mechanics",
    type: "mechanic",
    location: "Citywide Service",
    rating: 4.7,
    reviews: 89,
    description: "Professional mobile mechanic service. We come to you for convenient repairs.",
    services: ["Mobile Repair", "Diagnostics", "Battery Replacement", "Jump Start"],
    priceRange: "75-150",
  },
  {
    id: 3,
    name: "Premium Auto Parts",
    type: "parts",
    location: "Industrial District",
    rating: 4.8,
    reviews: 203,
    description: "Quality OEM and aftermarket parts with competitive prices and fast delivery.",
    services: ["OEM Parts", "Aftermarket Parts", "Delivery", "Installation"],
    priceRange: "25-500",
  },
  {
    id: 4,
    name: "QuickFix Auto Center",
    type: "garage",
    location: "Westside Mall",
    rating: 4.6,
    reviews: 156,
    description: "Fast and reliable automotive services with transparent pricing.",
    services: ["Quick Service", "Oil Change", "Tire Rotation", "Inspection"],
    priceRange: "40-120",
  },
  {
    id: 5,
    name: "Expert Engine Works",
    type: "mechanic",
    location: "North District",
    rating: 4.9,
    reviews: 94,
    description: "Specialized in engine repair and performance tuning with 15+ years experience.",
    services: ["Engine Repair", "Performance Tuning", "Diagnostics", "Rebuilds"],
    priceRange: "100-800",
  },
  {
    id: 6,
    name: "AutoZone Plus",
    type: "parts",
    location: "Multiple Locations",
    rating: 4.5,
    reviews: 312,
    description: "Wide selection of automotive parts and accessories with expert advice.",
    services: ["Parts Sales", "Tool Rental", "Battery Testing", "Installation Help"],
    priceRange: "15-300",
  },
]

// Dashboard data for different user types
export const dashboardData = {
  garage: [
    {
      title: "Monthly Revenue",
      value: "$12,450",
      change: "+15.2%",
      icon: DollarSign,
    },
    {
      title: "Active Customers",
      value: "89",
      change: "+8.1%",
      icon: Users,
    },
    {
      title: "Bookings This Month",
      value: "156",
      change: "+12.5%",
      icon: Calendar,
    },
    {
      title: "Average Rating",
      value: "4.8",
      change: "+0.2",
      icon: Star,
    },
  ],
  mechanic: [
    {
      title: "Monthly Earnings",
      value: "$8,750",
      change: "+18.3%",
      icon: DollarSign,
    },
    {
      title: "Jobs Completed",
      value: "47",
      change: "+22.1%",
      icon: Wrench,
    },
    {
      title: "Scheduled Jobs",
      value: "23",
      change: "+5.4%",
      icon: Calendar,
    },
    {
      title: "Customer Rating",
      value: "4.9",
      change: "+0.1",
      icon: Star,
    },
  ],
  parts: [
    {
      title: "Monthly Sales",
      value: "$15,680",
      change: "+11.7%",
      icon: DollarSign,
    },
    {
      title: "Orders Fulfilled",
      value: "234",
      change: "+19.2%",
      icon: Package,
    },
    {
      title: "Active Listings",
      value: "1,247",
      change: "+3.8%",
      icon: Car,
    },
    {
      title: "Customer Rating",
      value: "4.7",
      change: "+0.3",
      icon: Star,
    },
  ],
}

// Recent bookings
export const recentBookings = [
  {
    id: 1,
    customerName: "John Smith",
    service: "Oil Change & Filter",
    date: "2024-01-15",
    time: "10:00 AM",
    status: "confirmed"
  },
  {
    id: 2,
    customerName: "Sarah Johnson",
    service: "Brake Inspection",
    date: "2024-01-15",
    time: "2:30 PM",
    status: "pending",
  },
  {
    id: 3,
    customerName: "Mike Davis",
    service: "Engine Diagnostics",
    date: "2024-01-16",
    time: "9:00 AM",
    status: "confirmed",
  },
  {
    id: 4,
    customerName: "Lisa Wilson",
    service: "Tire Rotation",
    date: "2024-01-16",
    time: "3:00 PM",
    status: "completed",
  },
]

// Extended bookings data
export const allBookings = [
  ...recentBookings,
  {
    id: 5,
    customerName: "David Wilson",
    service: "Transmission Service",
    date: "2024-01-17",
    time: "11:00 AM",
    status: "pending",
    price: 180,
  },
  {
    id: 6,
    customerName: "Emma Thompson",
    service: "AC Repair",
    date: "2024-01-17",
    time: "1:30 PM",
    status: "confirmed",
    price: 95,
  },
  {
    id: 7,
    customerName: "James Brown",
    service: "Battery Replacement",
    date: "2024-01-18",
    time: "9:30 AM",
    status: "completed",
    price: 120,
  },
  {
    id: 8,
    customerName: "Sophie Davis",
    service: "Wheel Alignment",
    date: "2024-01-18",
    time: "2:00 PM",
    status: "cancelled",
    price: 75,
  },
]

// Recent reviews
export const recentReviews = [
  {
    id: 1,
    customerName: "Robert Brown",
    rating: 5,
    comment: "Excellent service! Fixed my car quickly and at a fair price. Highly recommend!",
    date: "2024-01-14",
  },
  {
    id: 2,
    customerName: "Emily Chen",
    rating: 4,
    comment: "Good work on my brake repair. Professional and courteous staff.",
    date: "2024-01-13",
  },
  {
    id: 3,
    customerName: "David Miller",
    rating: 5,
    comment: "Best garage in town! Always honest about what needs to be done.",
    date: "2024-01-12",
  },
]

// Extended reviews data
export const allReviews = [
  ...recentReviews,
  {
    id: 4,
    customerName: "Jennifer Martinez",
    rating: 5,
    comment:
      "Outstanding service! They went above and beyond to fix my car. The staff was professional and the pricing was fair.",
    date: "2024-01-11",
    service: "Engine Repair",
    response:
      "Thank you Jennifer! We're thrilled you had such a positive experience. We always strive to provide the best service possible.",
    responseDate: "2024-01-12",
  },
  {
    id: 5,
    customerName: "Michael Thompson",
    rating: 4,
    comment: "Good service overall. The work was done well, though I had to wait a bit longer than expected.",
    date: "2024-01-09",
    service: "Brake Repair",
    response: null,
    responseDate: null,
  },
  {
    id: 6,
    customerName: "Amanda Wilson",
    rating: 5,
    comment: "Excellent experience from start to finish. Very knowledgeable technicians and great customer service.",
    date: "2024-01-07",
    service: "Oil Change",
    response: "We appreciate your kind words Amanda! Our team takes pride in providing excellent service.",
    responseDate: "2024-01-08",
  },
  {
    id: 7,
    customerName: "Kevin Rodriguez",
    rating: 3,
    comment: "Service was okay. The issue was fixed but communication could have been better about the timeline.",
    date: "2024-01-06",
    service: "AC Repair",
    response: null,
    responseDate: null,
  },
  {
    id: 8,
    customerName: "Rachel Green",
    rating: 5,
    comment:
      "Amazing service! They diagnosed the problem quickly and fixed it at a reasonable price. Highly recommend!",
    date: "2024-01-05",
    service: "Diagnostics",
    response: "Thank you Rachel! We're so glad we could help get your car running smoothly again.",
    responseDate: "2024-01-06",
  },
  {
    id: 9,
    customerName: "Thomas Anderson",
    rating: 2,
    comment: "Not satisfied with the service. The problem wasn't fully resolved and I had to come back twice.",
    date: "2024-01-04",
    service: "Transmission",
    response: null,
    responseDate: null,
  },
  {
    id: 10,
    customerName: "Lisa Parker",
    rating: 4,
    comment: "Professional service and fair pricing. The only downside was the busy waiting area.",
    date: "2024-01-03",
    service: "Tire Service",
    response: "Thanks for the feedback Lisa! We're working on improving our waiting area comfort.",
    responseDate: "2024-01-04",
  },
]

// Marketplace listings
export const marketplaceListings = [
  {
    id: 1,
    name: "AutoCare Pro Garage",
    type: "garage",
    location: "Downtown, City Center",
    rating: 4.9,
    reviews: 127,
    description:
      "Full-service automotive repair with certified technicians and modern equipment. We specialize in all makes and models.",
    services: ["Oil Change", "Brake Repair", "Engine Diagnostics", "Transmission", "AC Service", "Tire Service"],
    priceRange: "50-200",
    availability: "Mon-Sat 8AM-6PM",
  },
  {
    id: 2,
    name: "Mike's Mobile Mechanics",
    type: "mechanic",
    location: "Citywide Service",
    rating: 4.7,
    reviews: 89,
    description: "Professional mobile mechanic service. We come to you for convenient repairs at your location.",
    services: ["Mobile Repair", "Diagnostics", "Battery Replacement", "Jump Start", "Emergency Service"],
    priceRange: "75-150",
    availability: "24/7 Emergency Service",
  },
  {
    id: 3,
    name: "Premium Auto Parts",
    type: "parts",
    location: "Industrial District",
    rating: 4.8,
    reviews: 203,
    description: "Quality OEM and aftermarket parts with competitive prices and fast delivery. Expert advice included.",
    services: ["OEM Parts", "Aftermarket Parts", "Delivery", "Installation", "Warranty"],
    priceRange: "25-500",
    availability: "Mon-Sun 7AM-9PM",
  },
  {
    id: 4,
    name: "QuickFix Auto Center",
    type: "garage",
    location: "Westside Mall",
    rating: 4.6,
    reviews: 156,
    description: "Fast and reliable automotive services with transparent pricing. No hidden fees guaranteed.",
    services: ["Quick Service", "Oil Change", "Tire Rotation", "Inspection", "Maintenance"],
    priceRange: "40-120",
    availability: "Mon-Fri 7AM-7PM",
  },
  {
    id: 5,
    name: "Expert Engine Works",
    type: "mechanic",
    location: "North District",
    rating: 4.9,
    reviews: 94,
    description:
      "Specialized in engine repair and performance tuning with 15+ years experience. European cars specialty.",
    services: ["Engine Repair", "Performance Tuning", "Diagnostics", "Rebuilds", "Custom Work"],
    priceRange: "100-800",
    availability: "Tue-Sat 9AM-5PM",
  },
  {
    id: 6,
    name: "AutoZone Plus",
    type: "parts",
    location: "Multiple Locations",
    rating: 4.5,
    reviews: 312,
    description: "Wide selection of automotive parts and accessories with expert advice. Price matching available.",
    services: ["Parts Sales", "Tool Rental", "Battery Testing", "Installation Help", "Returns"],
    priceRange: "15-300",
    availability: "Mon-Sun 6AM-10PM",
  },
  {
    id: 7,
    name: "City Auto Repair",
    type: "garage",
    location: "East Side",
    rating: 4.4,
    reviews: 78,
    description: "Family-owned garage serving the community for over 20 years. Honest pricing and quality work.",
    services: ["General Repair", "Bodywork", "Paint", "Restoration", "Classic Cars"],
    priceRange: "60-300",
    availability: "Mon-Fri 8AM-5PM",
  },
  {
    id: 8,
    name: "Roadside Heroes",
    type: "mechanic",
    location: "Highway Coverage",
    rating: 4.8,
    reviews: 156,
    description: "24/7 emergency roadside assistance and mobile repairs. Fast response time guaranteed.",
    services: ["Emergency Service", "Towing", "Lockout Service", "Flat Tire", "Jump Start"],
    priceRange: "50-200",
    availability: "24/7 Emergency",
  },
]

// Service categories
export const serviceCategories = [
  {
    id: "maintenance",
    name: "Maintenance",
    description: "Regular vehicle maintenance services",
    services: ["Oil Change", "Filter Replacement", "Fluid Check", "Tire Rotation"],
  },
  {
    id: "repair",
    name: "Repair",
    description: "Vehicle repair and diagnostics",
    services: ["Engine Repair", "Brake Repair", "Transmission", "Electrical"],
  },
  {
    id: "emergency",
    name: "Emergency",
    description: "24/7 emergency services",
    services: ["Roadside Assistance", "Towing", "Jump Start", "Lockout"],
  },
  {
    id: "parts",
    name: "Parts & Accessories",
    description: "Automotive parts and accessories",
    services: ["OEM Parts", "Aftermarket", "Tires", "Batteries"],
  },
]

// Business services data
export const businessServices = [
  {
    id: 1,
    name: "Oil Change & Filter",
    category: "maintenance",
    description: "Complete oil change service with premium oil and filter replacement",
    priceRange: "45-65",
    duration: "30 mins",
    rating: 4.8,
    reviews: 124,
    bookings: 89,
    avgPrice: 55,
    active: true,
  },
  {
    id: 2,
    name: "Brake Inspection & Repair",
    category: "repair",
    description: "Comprehensive brake system inspection and repair services",
    priceRange: "80-250",
    duration: "60-120 mins",
    rating: 4.9,
    reviews: 87,
    bookings: 45,
    avgPrice: 165,
    active: true,
  },
  {
    id: 3,
    name: "Engine Diagnostics",
    category: "diagnostics",
    description: "Advanced computer diagnostics to identify engine issues",
    priceRange: "90-150",
    duration: "45 mins",
    rating: 4.7,
    reviews: 56,
    bookings: 32,
    avgPrice: 120,
    active: true,
  },
  {
    id: 4,
    name: "Tire Rotation & Balance",
    category: "maintenance",
    description: "Professional tire rotation and wheel balancing service",
    priceRange: "35-55",
    duration: "45 mins",
    rating: 4.6,
    reviews: 78,
    bookings: 67,
    avgPrice: 45,
    active: true,
  },
  {
    id: 5,
    name: "AC System Service",
    category: "repair",
    description: "Air conditioning system repair and maintenance",
    priceRange: "75-180",
    duration: "90 mins",
    rating: 4.5,
    reviews: 43,
    bookings: 28,
    avgPrice: 125,
    active: true,
  },
  {
    id: 6,
    name: "Transmission Flush",
    category: "maintenance",
    description: "Complete transmission fluid replacement and system flush",
    priceRange: "120-200",
    duration: "75 mins",
    rating: 4.8,
    reviews: 34,
    bookings: 19,
    avgPrice: 160,
    active: false,
  },
]

// Customer data
export const customers = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    status: "active",
    totalBookings: 12,
    totalSpent: 1450,
    rating: 4.8,
    lastVisit: "2024-01-10",
    vehicles: [
      { year: 2019, make: "Toyota", model: "Camry", vin: "1HGBH41JXMN109186" },
      { year: 2021, make: "Honda", model: "Civic", vin: "2HGFC2F59MH123456" },
    ],
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 234-5678",
    status: "vip",
    totalBookings: 18,
    totalSpent: 2340,
    rating: 4.9,
    lastVisit: "2024-01-08",
    vehicles: [{ year: 2020, make: "BMW", model: "X3", vin: "5UXWX9C50L9A12345" }],
  },
  {
    id: 3,
    name: "Mike Davis",
    email: "mike.davis@email.com",
    phone: "+1 (555) 345-6789",
    status: "active",
    totalBookings: 8,
    totalSpent: 890,
    rating: 4.7,
    lastVisit: "2024-01-12",
    vehicles: [{ year: 2018, make: "Ford", model: "F-150", vin: "1FTFW1ET5JFA12345" }],
  },
  {
    id: 4,
    name: "Lisa Wilson",
    email: "lisa.wilson@email.com",
    phone: "+1 (555) 456-7890",
    status: "active",
    totalBookings: 15,
    totalSpent: 1780,
    rating: 4.6,
    lastVisit: "2024-01-05",
    vehicles: [{ year: 2017, make: "Nissan", model: "Altima", vin: "1N4AL3AP8HC123456" }],
  },
  {
    id: 5,
    name: "Robert Brown",
    email: "robert.brown@email.com",
    phone: "+1 (555) 567-8901",
    status: "inactive",
    totalBookings: 3,
    totalSpent: 320,
    rating: 4.2,
    lastVisit: "2023-11-15",
    vehicles: [{ year: 2016, make: "Chevrolet", model: "Malibu", vin: "1G1ZD5ST8GF123456" }],
  },
  {
    id: 6,
    name: "Emily Chen",
    email: "emily.chen@email.com",
    phone: "+1 (555) 678-9012",
    status: "vip",
    totalBookings: 22,
    totalSpent: 3120,
    rating: 4.9,
    lastVisit: "2024-01-14",
    vehicles: [
      { year: 2022, make: "Tesla", model: "Model 3", vin: "5YJ3E1EA8MF123456" },
      { year: 2019, make: "Audi", model: "A4", vin: "WAUENAF49KN123456" },
    ],
  },
]

// Chart data for dashboard
export const chartData = {
  revenue: [
    { month: "Jul", revenue: 8500 },
    { month: "Aug", revenue: 9200 },
    { month: "Sep", revenue: 8800 },
    { month: "Oct", revenue: 10500 },
    { month: "Nov", revenue: 11200 },
    { month: "Dec", revenue: 12450 },
  ],
  bookings: [
    { month: "Jul", bookings: 45 },
    { month: "Aug", bookings: 52 },
    { month: "Sep", bookings: 48 },
    { month: "Oct", bookings: 61 },
    { month: "Nov", bookings: 58 },
    { month: "Dec", bookings: 67 },
  ],
  services: [
    { name: "Oil Change", value: 35 },
    { name: "Brake Repair", value: 25 },
    { name: "Diagnostics", value: 20 },
    { name: "Other", value: 20 },
  ],
}
